#!/usr/bin/env php
<?php

require_once __DIR__.DIRECTORY_SEPARATOR.'public'.DIRECTORY_SEPARATOR.'.bootstrap.php';


$app = new Ahc\Cli\Application('dFramework', '3.0.0');

$app
    ->command('start', 'Start the PHP Dev Server for development of your application', 's')
        ->arguments('[port]', 'Le port sur lequel vous souhaitez lancer votre serveur de developpement')
        ->action(function($port) {
            $port = (empty($port) OR !is_numeric($port)) ? 3200 : intval($port);

            include_once __DIR__.DIRECTORY_SEPARATOR.'bin'.DIRECTORY_SEPARATOR.'start-server';
        });

$app->handle($_SERVER['argv']);
