#!/usr/bin/env php
<?php
/**
 * dFramework
 *
 * The simplest PHP framework for beginners
 * Copyright (c) 2019, Dimtrov Sarl
 * This content is released under the Mozilla Public License 2 (MPL-2.0)
 *
 * @package	    dFramework
 * @author	    Dimitri Sitchet Tomkeu <dev.dst@gmail.com>
 * @copyright	Copyright (c) 2019, Dimtrov Sarl. (https://dimtrov.hebfree.org)
 * @copyright	Copyright (c) 2019, Dimitri Sitchet Tomkeu. (https://www.facebook.com/dimtrovich)
 * @license	    https://opensource.org/licenses/MPL-2.0 MPL-2.0 License
 * @link	    https://dimtrov.hebfree.org/works/dframework
 * @version     3.2.1
 */

/*
 * --------------------------------------------------------------------
 * dFramework Command Line Interface
 * --------------------------------------------------------------------
 * The main entry point into the CLI system and allows you to run
 * commands and perform maintenance on your application.
 */

require_once __DIR__.DIRECTORY_SEPARATOR.'public'.DIRECTORY_SEPARATOR.'.bootstrap.php';


$app = new Ahc\Cli\Application('dFramework', dFramework\core\dFramework::VERSION);

$app->add(new dFramework\core\cli\Server, 'serve')
    ->add(new dFramework\core\cli\Mapper, 'map')
    ->add(new dFramework\core\cli\Tester, 'test')
    ->add(new dFramework\core\cli\Less)
    ->add(new dFramework\core\cli\Entity)
    ->add(new dFramework\core\cli\Migrate);
 
$app->handle($_SERVER['argv']);
