<?php 
/**
 * MembresEntity
 *
 * Generated by dFramework v3.2.2
 * Date : Thu, 24 Dec 2020 22:48:29 +0000
 * PHP Version : 7.2.19
 * Entity : Membres
 */
class MembresEntity extends dFramework\core\Entity
{
	/** @var string */
	protected static $table = 'membres';

	/** @var string[] */
	protected $pk = ['id_membre'];

	/** @var int */
	protected $idMembre;

	/** @var string */
	protected $nom;

	/** @var string */
	protected $prenom;

	/** @var mixed */
	protected $dateInscription;


	/**
	 * @return int
	 */
	public function getIdMembre(): int
	{
		return $this->idMembre;
	}


	/**
	 * @param int $idMembre
	 * @return self
	 */
	public function setIdMembre(int $idMembre): self
	{
		$this->idMembre = $idMembre;
		return $this;
	}


	/**
	 * @return string
	 */
	public function getNom(): string
	{
		return $this->nom;
	}


	/**
	 * @param string $nom
	 * @return self
	 */
	public function setNom(string $nom): self
	{
		$this->nom = $nom;
		return $this;
	}


	/**
	 * @return string
	 */
	public function getPrenom(): string
	{
		return $this->prenom;
	}


	/**
	 * @param string $prenom
	 * @return self
	 */
	public function setPrenom(string $prenom): self
	{
		$this->prenom = $prenom;
		return $this;
	}


	/**
	 * @return mixed
	 */
	public function getDateInscription()
	{
		return $this->dateInscription;
	}


	/**
	 * @param mixed $dateInscription
	 * @return self
	 */
	public function setDateInscription($dateInscription): self
	{
		$this->dateInscription = $dateInscription;
		return $this;
	}
}
