<?php

/*
| -------------------------------------------------------------------
| GENERAL SETTINGS OF APPLICATION
| -------------------------------------------------------------------
| This file will contain the generals settings of your application.
|
| For complete instructions please consult the 'General Configuration' in User Guide.
|
*/


/*
| URL to your dFramework root. Typically this will be your base URL, WITH a trailing slash: e.g: http://example.com/
|
| WARNING: You MUST set this value!
|
| If it is not set, then dFramework will try guess the protocol and path
| your installation, but due to security concerns the hostname will be set
| to $_SERVER['SERVER_ADDR'] if available, or localhost otherwise.
| The auto-detection mechanism exists only for convenience during
| development and MUST NOT be used in production!
|
| If you need to allow multiple domains, remember that this file is still
| a PHP script and you can easily do that on your own.
|
*/
$general['base_url'] = env('app.baseURL', '');

/*
| This option allows you to add a suffix to all URLs generated by the framework
| For more information please see the user guide:
*/
$general['url_suffix'] = '';

/*
| Specifie l'environement de travail dans lequel vous etes
|   - dev / prod
*/
$general['environment']	= env('ENVIRONMENT', 'dev');

/*
| Specifie si on doit afficher la debugbar ou pas
*/
$general['show_debugbar'] = true;

/*
| Specificie si on doit compresser le code de la vue avant de l'afficher ou pas
|   - True / False
|   - Auto : Le systeme compressera le code uniquement si vous passez dans un environement de production
*/
$general['compress_output'] = 'auto';

/*
| Specifie si les liens doivent etre en absolue (avec le nom de domaine) ou en relatif
*/
$general['use_absolute_link'] = true;

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$general['language']	= 'en';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
| See http://php.net/htmlspecialchars for a list of supported charsets.
|
*/
$general['charset'] = 'UTF-8';



/**
 * DON'T TOUCH THIS LINE. IT'S USING BY CONFIG CLASS
 */
return compact('general');
