<?php 
/**
 * MembresController
 *
 * Generated by dFramework v3.2.2
 * Date : Thu, 24 Dec 2020 23:33:22 +0000
 * PHP Version : 7.2.19
 * Controller : Membres
 */
class MembresController extends dFramework\core\Controller
{
	/**
	 * Accueil des membres
	 * Vous accederez a cette page via l'URL /membres
	 */
	public function index()
	{
		$datas = [];
		$datas['membres'] = $this->model->read();
		if (empty($datas['membres'])) {
			// Aucun(e) membre trouvé(e) en base de données
			// Traitements appropriés
		} else {
			// 1 ou plusieurs membres trouvé(e)s en base de données
			// Traitements appropriés
		}
		$this->view('index', $datas)->render();
	}


	/**
	 * Ajout d'un element dans la table membres
	 * Vous accederez a cette page via l'URL /membres/add
	 */
	public function add()
	{
		$datas = [];
		// Traitements quelconques
		if($this->request->is('post')) {
			try {
				$post = $this->request->data;
				foreach($post as $key => $value) {
					if(!in_array($key, ['nom','prenom','date_inscription'])) { unset($post[$key]); }
				}
				$this->loadLibrary('Checker');
				$this->checker->useInputField(true, $post);
				if(!$this->checker->inField('nom','prenom','date_inscription')) {
					// Champs incomplets
					// Traitements appropriés
					$datas['errors'] = 'Veuillez remplir tous les champs suivants : nom,prenom,date_inscription';
				} else {
					$id_membre = $this->model->create($post);
					redirect("membres/details/$id_membre");
				}
			}
			catch(\Exception $e) {
				// Une erreur s'est produite lors de la creation
				// Traitements appropriés: var_dump($e);
			}
		}
		// Traiments quelconques
		$this->view('add', $datas)->render();
	}


	/**
	 * Details d'un element de la table membres
	 * Vous accederez a cette page via l'URL /membres/details/{id_membre}
	 *
	 * @param mixed $id_membre
	 */
	public function details($id_membre)
	{
		$datas = [];
		$datas['membre'] = $this->model->read_pk($id_membre);
		if (empty($datas['membre'])) {
			// Aucun(e) membre correspondant(e) en base de données
			// Traitements appropriés
		} else {
			// Element trouvé
			// Traitements appropriés
		}
		$this->view('details', $datas)->render();
	}


	/**
	 * Modification d'un element de la table membres
	 * Vous accederez a cette page via l'URL /membres/update/{id_membre}
	 *
	 * @param mixed $id_membre
	 */
	public function update($id_membre)
	{
		$datas = [];
		$datas['membre'] = $this->model->read_pk($id_membre);
		if (empty($datas['membre'])) {
			// Aucun(e) membre correspondant(e) en base de données
			// Traitements appropriés
		} else {
			// Element trouvé
			// Traitements appropriés
			if($this->request->is('post')) {
				try {
					$post = $this->request->data;
					foreach($post as $key => $value) {
						if(!in_array($key, ['nom','prenom','date_inscription'])) { unset($post[$key]); }
					}
					$this->loadLibrary('Checker');
					$this->checker->useInputField(true, $post);
					if(!$this->checker->inField('nom','prenom','date_inscription')) {
						// Champs incomplets
						// Traitements appropriés
						$datas['errors'] = 'Veuillez remplir tous les champs suivants : nom,prenom,date_inscription';
					} else {
						$this->model->edit($id_membre, $post);
						redirect("membres/details/$id_membre");
					}
				}
				catch(\Exception $e) {
					// Une erreur s'est produite lors de la modification
					// Traitements appropriés: var_dump($e);
				}
			}
		}
		$this->view('update', $datas)->render();
	}


	/**
	 * Suppression d'un element de la table membres
	 * Vous accederez a cette page via l'URL /membres/delete/{id_membre}
	 *
	 * @param mixed $id_membre
	 */
	public function delete($id_membre)
	{
		try {
			$this->model->remove($id_membre);
			redirect('membres');
		}
		catch(\Exception $e) {
			// Une erreur s'est produite lors de la suppression
			// Traitements appropriés: var_dump($e);
		}
	}


	/**
	 * Suppression de tous les elemente de la table membres
	 * Vous accederez a cette page via l'URL /membres/delete-all
	 */
	public function delete_all()
	{
		try {
			$this->model->clear();
			redirect('membres');
		}
		catch(\Exception $e) {
			// Une erreur s'est produite lors de la suppression
			// Traitements appropriés: var_dump($e);
		}
	}
}
